### ISSUE TITLE
Nice to see development

### ISSUE THREAD

**Issue by Firminator** [NHellFire/dban#11]
Just found this Fork. Congratulations on continuing DBAN.
Long time user here. Usually using v1.0.7 and v1.0.7BETA. v2.2.6 usually never finished booting on dozens of different DELL systems (PowerEdge Servers, Desktops and  Laptops). In the past 2 or 3 years I found myself using more and more PartedMagic depending on the system; however PM doesn't support DELL PERCs.

If I could just ask for a few things for future versions: keep it simple and don't add too many new features. KISS. We need a fast-booting, auto-starting wiping tool. Make overwriting with 0 the default, no blanking pass, no verification, just 1 pass.
I haven't used the last v2.2.8, but I'm interested if it works on DELL PowerEdge 2950, R710, R720 and T610 with a DELL PERC 5/i, PERC 6/i, PERC, Hx00i etc.

**Comment by NHellFire** [comment]
I'm trying to keep it simple. Most things should be just bug or usability fixes.
As I've updated the kernel, the PERC controllers (at least 5 and H200) should be supported now. The drivers for them are enabled, but I don't have one I can test on.
