### ISSUE TITLE
MBR fingerprint announces "pass" even if verification errors occurred

### ISSUE THREAD

**Issue by Himotestaaja** [NHellFire/dban#12]
MBR fingerprint announces "pass" even if verification errors occurred.

**Comment by NHellFire** [comment]
Tomorrow I'll have a test build for you to try. It should then report a successful wipe, but failed verification in your case.

**Comment by NHellFire** [comment]
Sorry it took so long, been busy and nearly forgot about this.
This build should fix this issue: https://github.com/NHellFire/dban/releases/tag/v3.0.2-beta1
