### ISSUE TITLE
Beep, flash leds when finished

### ISSUE THREAD

**Issue by kvlahromei** [NHellFire/dban#15]
It would be a nice feature, if the PC could beep / blink with keyboard leds, to notify you that the progress is finished. If you have to wipe a dozen PCs, you don't monitor them for hours. You probally don't keep them connected via KVM, so a speaker sound would be nice.

(Currently an ordinary stopwatch-alarm does the job)

**Comment by NHellFire** [comment]
Just added flashing keyboard LEDs when finished. Not sure if there's much point adding beep as most motherboards don't have a speaker anymore.

**Comment by kvlahromei** [comment]
@NHellFire  Thanks for the fix :smile: 

I'm not sure about the speaker support. IMHO the speaker is emulated / redirected by the soundcard if there is no speaker in the case. But hey, this is just an comfort feature :wink:
