### ISSUE TITLE
ACPI shutdown if finished successfully

### ISSUE THREAD

**Issue by kvlahromei** [NHellFire/dban#16]
It would be nice, if you could fireup DBAN machines for the night, but don't want to waste energy. So maybe it's possible, that the machine shutsdown itself, if after hours the job was finished successfully ?

**Comment by NHellFire** [comment]
Just added this. Automatic shutdown 1 hour after completion, but only if all disks were successfully wiped.

**Comment by kvlahromei** [comment]
@NHellFire Thank you :+1:
