### ISSUE TITLE
ISO image that can also be booted from USB

### ISSUE THREAD

**Issue by lassik** [NHellFire/dban#19]
Hello,

Nice to see there is ongoing development on this very handy utility!

Do you know how difficult it would be to create an ISO image that also boots from USB without modification? Then one could just download an ISO image and write it to a USB stick using `cat` as some Linux distribution ISOs can.

I just spent an hour figuring out how to get the official DBAN onto a USB stick, ended up using [this complicated procedure](https://github.com/lassik/notes/blob/master/make-dban-usb-stick-on-mac.md) and thought a simple `cat` would be a lot nicer :)

Apologies if this feature is already included or prohibitively difficult to do. I couldn't find any mention in the issue tracker or commit logs and don't have any relevant expertise myself.

KR,
Lassi

**Comment by NHellFire** [comment]
Writing the ISO directly to the whole device with dd/cat should work for booting on most systems.

**Comment by NHellFire** [comment]
Just replaced the v3.0.1 ISO with one that works when directly written to a USB drive.
