### ISSUE TITLE
Flattr link gives error.

### ISSUE THREAD

**Issue by Forbo** [NHellFire/dban#20]
When attempting to donate with the Flattr link, it simply shows the following:
![screen shot 2016-07-20 at 15 00 44](https://cloud.githubusercontent.com/assets/6404250/17002926/e059b810-4e8a-11e6-9cc7-474f41517c4f.png)

**Comment by NHellFire** [comment]
Link is correct, so should work. Using adblock, noscript or anything similar?

**Comment by Forbo** [comment]
In my primary browser, yes. However, when I ran into this problem I tried it on two other browsers that do not have any plugins whatsoever, yielding the same result. I tried on a completely different computer and browser, and am getting the same result. It appears to be an issue with my Flattr account. Sorry for the confusion. :-\

**Comment by Forbo** [comment]
Sorry to reopen and comment on this, but I got a response back from Flattr as follows:

"Hi
Sorry bit github URL's can be flattr right now, but you can flattr via their flattr profile https://flattr.com/profile/NHellFire

Regards Linus"

So it sounds like the referral link portion is broken at the moment, if I'm understanding it correctly.
