### ISSUE TITLE
Fails to compile with GCC 6

### ISSUE THREAD

**Issue by mtdew365** [NHellFire/dban#22]
In file included from tm.h:46:0,
                 from insn-recog.c:7:
../../gcc/defaults.h:126:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
rm gcc.pod
Makefile:3973: recipe for target 'all-gcc' failed
make[4]: *** [all-gcc] Error 2
Makefile:860: recipe for target 'all' failed
make[3]: *** [all] Error 2
package/pkg-generic.mk:196: recipe for target '/home/jbergmann/buildroot/output/build/host-gcc-final-4.9.3/.stamp_built' failed
make[2]: *** [/home/jbergmann/buildroot/output/build/host-gcc-final-4.9.3/.stamp_built] Error 2
Makefile:36: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/jbergmann/buildroot'
Makefile:6: recipe for target 'i586' failed
make: *** [i586] Error 2

Version is 30c1b515147efd55c8085a895893689269542d46.
I believe it might be something with gcc-final-4.9.3....  The last compile that was successful was 20160514.

**Comment by NHellFire** [comment]
I haven't changed anything in buildroot recently.

1. Your log doesn't contain any useful parts of the errors.
2. Your paths are strange.
/home/jbergmann/buildroot? The DBAN buildroot will be in the same folder
you cloned the dban repo to. So, if it was in ~/dban, it'd be using our
buildroot in ~/dban/buildroot

FWIW, I've built it 3 times today while testing automatic uploading of
builds.

**Comment by mtdew365** [comment]
I get buildroot in from "git clone https://github.com/NHellFire/dban-buildroot.git $HOME/buildroot" and
I get dban in from "git clone https://github.com/NHellFire/dban.git $HOME/dban".
I create a link from $HOME/dban to $HOME/buildroot.
I will keep looking at the file and see if I can get some useful parts to attach to this ticket.

**Comment by mtdew365** [comment]
This is the script that has worked before...
#!/bin/bash

echo "Compiling DBAN"
cd $HOME/dban/buildroot
make clean
make ARCH=i586
cd $HOME/dban
make
sudo sh -c "./master.sh"
now=$(date +"%Y%m%d")
rename ~pre _$now *.iso

Am I doing something incorrect?

**Comment by mtdew365** [comment]
I just tried again.  I hope this has more useful information....
In file included from ./tm.h:46:0,
                 from ../../gcc/cp/except.c:27:
../../gcc/defaults.h:126:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ../../gcc/cp/except.c:1013:0:
cfns.gperf: In function ‘const char* libc_name_p(const char*, unsigned int)’:
cfns.gperf:101:1: error: ‘const char* libc_name_p(const char*, unsigned int)’ redeclared inline with ‘gnu_inline’ attribute
cfns.gperf:26:14: note: ‘const char* libc_name_p(const char*, unsigned int)’ previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function ‘const char* libc_name_p(const char*, unsigned int)’ used but never defined
Makefile:1058: recipe for target 'cp/except.o' failed
make[5]: *** [cp/except.o] Error 1
make[5]: *** Waiting for unfinished jobs....
In file included from ./tm.h:29:0,
                 from ../../gcc/cp/mangle.c:50:
../../gcc/config/elfos.h:102:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
    fprintf ((FILE), "%s"HOST_WIDE_INT_PRINT_UNSIGNED"\n",\
                     ^
../../gcc/config/elfos.h:170:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:46:0,
                 from ../../gcc/cp/mangle.c:50:
../../gcc/defaults.h:126:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:29:0,
                 from ../../gcc/cp/name-lookup.c:24:
../../gcc/config/elfos.h:102:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
    fprintf ((FILE), "%s"HOST_WIDE_INT_PRINT_UNSIGNED"\n",\
                     ^
../../gcc/config/elfos.h:170:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:46:0,
                 from ../../gcc/cp/name-lookup.c:24:
../../gcc/defaults.h:126:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:29:0,
                 from ../../gcc/function.h:26,
                 from ../../gcc/cp/cp-tree.h:25,
                 from ../../gcc/cp/cp-cilkplus.c:26:
../../gcc/config/elfos.h:102:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
    fprintf ((FILE), "%s"HOST_WIDE_INT_PRINT_UNSIGNED"\n",\
                     ^
../../gcc/config/elfos.h:170:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:46:0,
                 from ../../gcc/function.h:26,
                 from ../../gcc/cp/cp-tree.h:25,
                 from ../../gcc/cp/cp-cilkplus.c:26:
../../gcc/defaults.h:126:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
/bin/sh ../../gcc/../move-if-change tmp-automata.c insn-automata.c
echo timestamp > s-automata
In file included from ./tm.h:29:0,
                 from ../../gcc/cp/cxx-pretty-print.c:24:
../../gcc/config/elfos.h:102:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
    fprintf ((FILE), "%s"HOST_WIDE_INT_PRINT_UNSIGNED"\n",\
                     ^
../../gcc/config/elfos.h:170:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:46:0,
                 from ../../gcc/cp/cxx-pretty-print.c:24:
../../gcc/defaults.h:126:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:29:0,
                 from ../../gcc/cp/cp-gimplify.c:25:
../../gcc/config/elfos.h:102:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
    fprintf ((FILE), "%s"HOST_WIDE_INT_PRINT_UNSIGNED"\n",\
                     ^
../../gcc/config/elfos.h:170:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:46:0,
                 from ../../gcc/cp/cp-gimplify.c:25:
../../gcc/defaults.h:126:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:29:0,
                 from ../../gcc/function.h:26,
                 from ../../gcc/cp/cp-tree.h:25,
                 from ../../gcc/cp/cp-array-notation.c:57:
../../gcc/config/elfos.h:102:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
    fprintf ((FILE), "%s"HOST_WIDE_INT_PRINT_UNSIGNED"\n",\
                     ^
../../gcc/config/elfos.h:170:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:46:0,
                 from ../../gcc/function.h:26,
                 from ../../gcc/cp/cp-tree.h:25,
                 from ../../gcc/cp/cp-array-notation.c:57:
../../gcc/defaults.h:126:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
../../gcc/cp/cp-array-notation.c: In function ‘bool cilkplus_an_triplet_types_ok_p(location_t, tree, tree, tree, tree)’:
../../gcc/cp/cp-array-notation.c:1439:45: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
   if (!TREE_CODE (type) == FUNCTION_TYPE)
                                             ^ 
../../gcc/cp/cp-array-notation.c:1439:45: warning: comparison of constant ‘21’ with boolean expression is always false [-Wbool-compare]
   if (!TREE_CODE (type) == FUNCTION_TYPE)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ^               
rm gcc.pod
Makefile:3973: recipe for target 'all-gcc' failed
make[4]: *** [all-gcc] Error 2
Makefile:860: recipe for target 'all' failed
make[3]: *** [all] Error 2
package/pkg-generic.mk:196: recipe for target '/home/jbergmann/buildroot/output/build/host-gcc-final-4.9.3/.stamp_built' failed
make[2]: *** [/home/jbergmann/buildroot/output/build/host-gcc-final-4.9.3/.stamp_built] Error 2
Makefile:36: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/jbergmann/buildroot'
Makefile:6: recipe for target 'i586' failed
make: *** [i586] Error 2

I am not really good at programming but I will try any suggestions.

**Comment by NHellFire** [comment]
What GCC version are you running? ´gcc -v´
I'm not getting any failures with GCC 5.4 on Ubuntu 16.04 when building
master

**Comment by mtdew365** [comment]
gcc version 6.1.1 20160621 (Red Hat 6.1.1-3) (GCC)

**Comment by mtdew365** [comment]
Thanks for chasing this down!

**Comment by mtdew365** [comment]
Manually applied patch 233720 to gcc.  Trying to compile and burn a CD.

**Comment by mtdew365** [comment]
I received the following error....

checking whether your compiler passes the ACC conformance test... FAILED
configure: 
configure: Your compiler failed the ACC conformance test - for details see 
configure: `config.log'. Please check that log file and consider sending
configure: a patch or bug-report to <lzop-bugs@oberhumer.com>.
configure: Thanks for your support.
configure: 
configure: error: ACC conformance test failed. Stop.
package/pkg-generic.mk:186: recipe for target '/home/jbergmann/buildroot/output/build/host-lzop-1.03/.stamp_configured' failed
make[1]: *** [/home/jbergmann/buildroot/output/build/host-lzop-1.03/.stamp_configured] Error 1
Makefile:36: recipe for target '_all' failed
make: *** [_all] Error 2
make: Leaving directory '/home/jbergmann/buildroot'

I will just wait for your patch :)

**Comment by NHellFire** [comment]
I've cherry picked those 2 patches from latest buildroot now. I'll add GCC 6 to one of my virtual machines and see if there's any others I need to take.

**Comment by NHellFire** [comment]
I needed to check the PPC build too, both built fine.
