### ISSUE TITLE
able to support skylake chipsets

### ISSUE THREAD

**Issue by Francis1985** [NHellFire/dban#23]
Just wondering if this version is able to support skylake chipsets......

**Comment by NHellFire** [comment]
It should work. I've not had any reports of it not working on skylake. I'm
unable to test as I don't have access to any skylake systems.

**Comment by Francis1985** [comment]
nope, not working..... with Z170

**Comment by NHellFire** [comment]
No drives detected? What version did you try?

**Comment by Phoenix09** [comment]
@Francis1985, how is anyone supposed to help you when you give no information?
>not working

doesn't tell anyone anything.

does it boot?
do you get an error message?
are drives detected?

Nightly 20160909-g399b37a boots on my Skylake laptop and all my SATA drives are detected.

**Comment by Francis1985** [comment]
It hangs at the screen with all the loading words.......... did not even hit the menu, using the latest version

**Comment by Phoenix09** [comment]
you still haven't provided any useful information.
take a **readable** photo of it.
without knowing why it gets stuck booting there isn't anything anyone can do.

all I can say is it works on my Skylake laptop and don't have access to a desktop to test.

**Comment by NHellFire** [comment]
No info provided. Works for @Phoenix09. Closing.
