### ISSUE TITLE
Strange URLs in buildscript

### ISSUE THREAD

**Issue by tuxflo** [NHellFire/dban#26]
I'm trying to build dban from the scratch using the steps described in the Readme.md. However I found some strange URLs connections in the output of the buildroot compiling process like "gutscheinrausch.de" and "bothelp.de" although I cannot find those URLs grepping through the directory.
Do you know whats up with this behavior?

Thanks for helping,
Flo

**Comment by NHellFire** [comment]
Those sites are official gnu.org mirrors: https://www.gnu.org/prep/ftp.en.html

**Comment by tuxflo** [comment]
Ok, thanks a lot for clearing this out so quick.
