### ISSUE TITLE
Add an "Easy Mode" or "Easy Edition" with a menu

### ISSUE THREAD

**Issue by aakatz3** [NHellFire/dban#27]
While I find the present version of DBAN easy to use, many people at my work help desk have issues with the boot loader and menu system. Would it be possible to make a basic menu that included the most common options, such as autowipe, quick, dodshort, and interactive, even if it is a separate image?

This is a feature request/enhancement.

**Comment by NHellFire** [comment]
I'll hopefully switch it to a menu soon

**Comment by Firminator** [comment]
FYI tested the new menu on a DELL T710 using a 3rd-party LSI SAS9211-4i (instead of a PERC H700 which doesn't pass-through the disks) with 16 attached 2.5" disks. Selected 'Quick' and it booted fine and auto-wiped all 16 disks simultaneously.
