### ISSUE TITLE
Network Connectivity Not Working on Some Machines

### ISSUE THREAD

**Issue by rmtworks** [NHellFire/dban#30]
Hello,
For the majority of the machines I'm erasing, the network works fine for saving a log and syncing the NTP client. However, I've noticed on some older Dell laptops I'm erasing, such as the Latitude D830 and D630, it doesn't appear the networking works. It never shows the DHCP or NTP client running during startup like my other machines do.

I found the Ethernet Controller model for the D630 (and I'd assume it's shared with the D830) is a Broadcom NetXtreme 5755M. Any ideas on what could be causing DBAN to not work with this controller? Thanks in advance!

**Comment by NHellFire** [comment]
Broadcom network drivers weren't enabled
https://github.com/NHellFire/dban/releases/tag/nightly%2F20171130-gf599a87 This build (and newer) should work now that the drivers are enabled.

**Comment by rmtworks** [comment]
Tested on a machine today and it worked! Thank you so much!
