### ISSUE TITLE
Will not compile latest version

### ISSUE THREAD

**Issue by mtdew365** [NHellFire/dban#31]
Fedora release 27 (Twenty Seven)
x86_64 Linux 4.13.15-300.fc27.x86_64

receive error when trying to compile dban....

>>> util-linux 2.28 Configuring
>>> util-linux 2.28 Autoreconfiguring
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /home/jbergmann/buildroot/output/host/usr/bin/automake line 3936.
autoreconf: /home/jbergmann/buildroot/output/host/usr/bin/automake failed with exit status: 255
make[2]: *** [package/pkg-generic.mk:193: /home/jbergmann/buildroot/output/build/util-linux-2.28/.stamp_configured] Error 1
make[1]: *** [Makefile:41: _all] Error 2
make[1]: Leaving directory '/home/jbergmann/buildroot'
make: *** [Makefile:9: i586] Error 2

**Comment by NHellFire** [comment]
Incompatibility with Perl v5.26 apparently. What version are you building? "latest version" isn't specific. Latest master? Latest stable?

**Comment by NHellFire** [comment]
Merged automake patch to master, please pull and try building again.

**Comment by mtdew365** [comment]
Downloaded latest master for buildroot (..caf48e83f) and for dban (..2e83bbd).  Rebuilding now...

**Comment by mtdew365** [comment]
Compiled correctly.
