### ISSUE TITLE
Supported HBA Controllers

### ISSUE THREAD

**Issue by Firminator** [NHellFire/dban#34]
Could you provide a list or some kind of reference which HBA controllers/chipset (i.e. LSI, Syba, HighPoint) are supported.
In https://github.com/NHellFire/dban/issues/11#issuecomment-118674881 you mentioned DELL PERC5 and PERC H200 are supported.
How can I check for example if Marvel 88SE91xx ( https://origin-www.marvell.com/storage/system-solutions/assets/Marvell-88SE91XX-Host-Controllers.pdf ) is supported.

The LSI MegaRAID SAS9211-4i and -8i works great btw.
Should this go into the Wiki?

**Comment by NHellFire** [comment]
Any controller supported by Linux (without requiring a manufacturer provided driver) should work fine. Not sure if I'll be able to provide a full list, the drivers mainly reference chipsets, not specific cards.

Any SATA controller should work (though recent AMD/Intel chipsets may require me to add their IDs) . Marvell SAS controllers are hit and miss due to the open-source driver not supporting some cards very well. 

Though, I'll have a look and see if I can make a fairly complete list of supported chipsets.

**Comment by Firminator** [comment]
If you have a link to a list of drivers for the chipsets that would be fine. I can derive the information I need from this. I'm having a hard time finding a reference list of supported hba and/or raid controller for the linux kernel.

**Comment by NHellFire** [comment]
Kernel config is [here](https://github.com/NHellFire/dban-buildroot/blob/dban/target/dban/linux-i586.config). The options of interest are `CONFIG_SCSI_*` and `CONFIG_SATA_*`

Summary assembled from v3.0.1 is:
hpsa - HP Smart Array SCSI driver
3w_9xxx - 3ware 9xxx SATA-RAID support
atp870u - ACARD SCSI support
aacraid - Adaptec AACRAID support
aic7xxx - Adaptec AIC7xxx Fast -> U160 support (New Driver)
aic79xx - Adaptec AIC79xx U320 support
aic94xx - Adaptec AIC94xx SAS/SATA support
mvsas - Marvell 88SE64XX/88SE94XX SAS/SATA support
dpt_i2o - Adaptec I2O RAID support
advansys - AdvanSys SCSI support
arcmsr - ARECA (ARC11xx/12xx/13xx/16xx) SATA/SAS RAID Host Adapter
mpt2sas - LSI MPT Fusion SAS 2.0 Device Driver
hptiop - HighPoint RocketRAID 3xxx/4xxx Controller support
BusLogic - BusLogic & FlashPoint SCSI support
dmx3191d - DMX3191D SCSI support
eata - EATA ISA/EISA/PCI (DPT and generic EATA/DMA-compliant boards) support
fdomain - Future Domain 16xx SCSI/AHA-2920A support
gdth - Intel/ICP (former GDT SCSI Disk Array) RAID Controller support
ips - IBM ServeRAID support
initio - Initio 9100U(W) support
a100u2w - Initio INI-A100U2W support
stex - Promise SuperTrak EX Series support
sym53c8xx - SYM53C8XX Version 2 SCSI support
ipr - IBM Power Linux RAID adapter support
qla1280 - Qlogic QLA 1240/1x80/1x160 SCSI support
dc395x - Tekram DC395(U/UW/F) and DC315(U) SCSI support
tmscsim - Tekram DC390(T) and Am53/79C974 SCSI support
nsp32 - Workbit NinjaSCSI-32Bi/UDE support
ahci - SATA Port Multiplier support
ahci - AHCI SATA support
sata_inic162x - Initio 162x SATA support (Very Experimental)
sata_sil24 - Silicon Image 3124/3132 SATA support
sata_qstor - Pacific Digital SATA QStor support
sata_sx4 - Promise SATA SX4 support (Experimental)
sata_mv - Marvell SATA support
sata_nv - NVIDIA SATA support
sata_promise - Promise SATA TX2/TX4 support
sata_sil - Silicon Image SATA support
sata_sis - SiS 964/965/966/180 SATA support
sata_svw - ServerWorks Frodo / Apple K2 SATA support
sata_uli - ULi Electronics SATA support
sata_via - VIA SATA support
sata_vsc - VITESSE VSC-7174 / INTEL 31244 SATA support


I believe the only changes in nightly are:
Added: mpt3sas - LSI MPT Fusion SAS 3.0 & SAS 2.0 Device Driver
Removed: tmscsim - Tekram DC390(T) and Am53/79C974 SCSI support (was replaced with a new driver that needs to be enabled)

**Comment by Firminator** [comment]
Thanks. That's what I was looking for.

**Comment by Firminator** [comment]
Thanks for adding the list of supported controllers to the [Wiki](https://github.com/NHellFire/dban/wiki/Supported-Hardware). Very much appreciated.
