### ISSUE TITLE
nousb flag not working in dban-20180606-g0954027_linux-4.7.2_i586

### ISSUE THREAD

**Issue by BrewCityGeek** [NHellFire/dban#35]
When selecting internal drive only automatic selection, my USB flash drive was wiped. I thought I did something wrong so I tried a different drive. Same behavior. Previously this flag could be used to ignore all USB devices.

**Comment by NHellFire** [comment]
Can you try `usbcore.nousb`, rather than just `nousb`? It's a kernel argument, and it looks like it was renamed at some point.

**Comment by BrewCityGeek** [comment]
Looks like that did the trick. Modified the config file with `usbcore.nousb` worked for me.
