### ISSUE TITLE
Moving to ShredOS

### ISSUE THREAD

**Issue by Firminator** [NHellFire/dban#37]
NHellFire,
I'm moving to [ShredOS 2020](https://github.com/PartialVolume/shredos.x86_64) but wanted to thank you for your initiative taking over DBAN, developing and maintaining this invaluable tool over the last years.
Happy coding.

**Comment by PartialVolume** [comment]
[Shredos 2020](https://github.com/PartialVolume/shredos.x86_64)

**Comment by Firminator** [comment]
Thx, corrected the ShredOS link (removed trailing comma).
