### ISSUE TITLE
lshw crashes with certain attached devices

### ISSUE THREAD

**Issue by NHellFire** [NHellFire/dban#4]
Certain devices cause lshw to crash resulting in no disk labels in dwipe.

Known devices:
* Kingston DataTraveler 100 G3

Waiting for lshw's SVN to be fixed to try latest version.

**Comment by Firminator** [comment]
If time allows, would you mind updating from currently used B.02.17-r2575 to https://ezix.org/src/pkg/lshw/archive/B.02.18.tar.gz ?

Changes:
- IBM pSeries enhancements
- bug fixes
- code cleanup
- updated data files

Changelog is here: https://ezix.org/project/wiki/HardwareLiSter#Changes

The B.02.18 release is from 2016 so the 'updated data files' are now outdated :(
If you can please update the included usb.ids (2016-03) and pci.ids (2016-04) with the latest version from 2019:

- usb.ids: http://www.linux-usb.org/usb.ids
- pci.ids: https://pci-ids.ucw.cz/v2.2/pci.ids
